---
- name: include os variables
  include_vars: "{{yui_compressor_os}}.yml"
  when: yui_compressor_os is defined and yui_compressor_os != ""

################################################################################################

- name: install yui-compressor
  apt: pkg={{yui_compressor_package}} state=present update_cache=yes cache_valid_time=3600